name: botbenin
description: Waouh Chat - BotBenin Flutter client.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  provider: ^6.1.5
  shared_preferences: ^2.5.4
  go_router: ^14.0.0
  image_picker: ^1.0.7
  flutter_slidable: ^3.0.1
  nowa_runtime: ^0.1.3
  dio: ^5.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
