
INSERT INTO public.support_knowledge_articles (title, content, module, category, keywords, display_order)
SELECT * FROM (VALUES
('Connexion impossible à la plateforme', E'Si vous ne parvenez pas à vous connecter à SIGDSTS :\n1. Vérifiez votre identifiant et mot de passe (sensibles à la casse)\n2. Vérifiez votre connexion Internet\n3. Si vous êtes administrateur, validez le code 2FA reçu par email\n4. Effacez le cache du navigateur (Ctrl+Shift+Suppr)\n5. Essayez avec un autre navigateur (Chrome ou Edge recommandés)\n6. Si l''erreur persiste, contactez le support N2 avec une capture d''écran de l''erreur.', 'Connexion', 'Authentification', ARRAY['connexion','login','mot de passe','2FA','authentification'], 1),
('Procédure de connexion étape par étape', E'Pour vous connecter à SIGDSTS :\n1. Ouvrez votre navigateur et accédez à l''URL de la plateforme\n2. Saisissez votre identifiant professionnel\n3. Saisissez votre mot de passe\n4. Cliquez sur "Se connecter"\n5. Si vous êtes administrateur : validez le code 2FA\n6. Vous arrivez sur le tableau de bord adapté à votre profil', 'Connexion', 'Authentification', ARRAY['connexion','procédure','tableau de bord'], 2),
('Module Accueil Donneur - Rechercher un donneur', E'Pour rechercher un donneur existant :\n1. Accédez au module "Accueil Donneur"\n2. Recherchez par : nom, prénom, numéro de donneur, ou téléphone\n3. Cliquez sur le résultat pour ouvrir la fiche\n4. Si le donneur n''existe pas, cliquez sur "Créer un nouveau donneur"', 'Accueil Donneur', 'Recherche', ARRAY['donneur','recherche','accueil','fiche'], 3),
('Créer un nouveau donneur - Fiche Pré-Don', E'Création en 4 étapes :\nÉTAPE 1 - État civil : nom, prénom, date de naissance, sexe, pièce d''identité\nÉTAPE 2 - Informations complémentaires : profession, antécédents\nÉTAPE 3 - Adresse géographique : département, commune, contact\nÉTAPE 4 - Photo du donneur\nFINALISATION : validez. Le donneur reçoit un numéro unique.', 'Accueil Donneur', 'Création', ARRAY['nouveau donneur','création','pré-don'], 4),
('Sélection Médicale - Questionnaire médical (Phase 1)', E'1. Accédez à la liste des fiches pré-don\n2. Sélectionnez le donneur\n3. Remplissez le questionnaire complet (antécédents, comportements à risque, médication)\n4. Toutes les questions doivent être répondues\n5. Sauvegardez régulièrement', 'Sélection Médicale', 'Questionnaire', ARRAY['sélection','questionnaire','phase 1'], 5),
('Sélection Médicale - Examen et décision (Phases 2-3)', E'PHASE 2 - Examen : TA, pouls, poids, hémoglobine, examen clinique\nPHASE 3 - Décision :\n- Apte au don : passe au prélèvement\n- Inapte temporaire : préciser durée et motif\n- Inapte définitif : préciser motif médical\nLa décision est tracée et signée numériquement.', 'Sélection Médicale', 'Décision', ARRAY['examen','décision','apte','inapte'], 6),
('Prélèvement - Générer numéros de poche', E'1. Module Prélèvement > "Générer numéros de poche"\n2. Saisissez la quantité nécessaire\n3. Le système attribue des numéros uniques\n4. Imprimez les codes-barres\nATTENTION : un numéro de poche ne peut être réutilisé.', 'Prélèvement', 'Préparation', ARRAY['prélèvement','poche','code-barres'], 7),
('Prélèvement - Enregistrer un prélèvement', E'1. Scannez le code-barres de la poche\n2. Sélectionnez le donneur (apte)\n3. Renseignez : volume, type de poche, agent, heures début/fin\n4. Validez. Le prélèvement passe à Préparation des PSL.\n5. Imprimez l''étiquette définitive', 'Prélèvement', 'Enregistrement', ARRAY['prélèvement','enregistrement','volume'], 8),
('Préparation des PSL - Créer un produit dérivé', E'1. Module Préparation des PSL > "Créer produit dérivé"\n2. Sélectionnez la poche mère\n3. Choisissez le type : CGR, PFC, CPS, etc.\n4. Renseignez le volume\n5. Date de péremption calculée auto selon le référentiel\n6. Imprimez l''étiquette avec QR code', 'Préparation PSL', 'Production', ARRAY['PSL','produit dérivé','CGR','PFC'], 9),
('Durées de vie des PSL (référentiel)', E'- CGR : 42 jours à 4°C\n- PFC : 1 an à -25°C\n- CPS : 5 jours à 22°C sous agitation\n- Sang Total : 35 jours à 4°C\n- Cryoprécipité : 1 an à -25°C\nDate de péremption auto-calculée à la création.', 'Préparation PSL', 'Référentiel', ARRAY['péremption','durée vie','CGR','PFC'], 10),
('Qualification Biologique - Sérologie', E'Étape 1 - Sérologie (VIH, VHB, VHC, Syphilis) :\n1. Module Qualification > Nouvelle qualification\n2. Scannez le code-barres\n3. Saisissez les résultats\n4. Si positif : poche marquée NON CONFORME automatiquement\n5. Donneur notifié et exclu temporairement', 'Qualification Biologique', 'Sérologie', ARRAY['sérologie','VIH','qualification'], 11),
('Qualification Biologique - Groupage sanguin (double contrôle)', E'Étape 3 - Groupage par 2 agents :\n- Agent 1 saisit son interprétation ABO/Rh\n- Agent 2 saisit indépendamment\n- Système compare et alerte si discordance\n- Concordance : groupe validé\n- Discordance : reprise avec un 3e agent\nGarantit la sécurité transfusionnelle.', 'Qualification Biologique', 'Groupage', ARRAY['groupage','ABO','Rh','sécurité'], 12),
('Tri & Validation', E'Analyse physique :\n1. Inspection visuelle (couleur, intégrité, hémolyse)\n2. Vérification soudures et étiquette\n3. Statut : CONFORME / NON CONFORME (motif)\n4. Mise à jour automatique\n5. Fiche produit avec QR code pour traçabilité', 'Tri & Validation', 'Analyse', ARRAY['tri','validation','conforme','QR'], 13),
('Distribution des PSL', E'Distribution via la BDS :\n1. Réception de la demande nominative (FDN)\n2. Vérification compatibilité ABO/Rh\n3. Édition du bon de sortie\n4. Scan du PSL distribué\n5. Statut "Distribué"\nSLA : Critique 2h | Haute 4h | Standard 24h', 'Distribution', 'PSL', ARRAY['distribution','BDS','FDN','SLA'], 14),
('Fiche d''Effets Indésirables (FEIR)', E'En cas d''effet indésirable post-transfusion :\n1. Module Distribution > FEIR\n2. Sélectionnez la transfusion (numéro PSL)\n3. Décrivez l''effet : type, gravité, délai\n4. Joignez documents (photo, compte-rendu)\n5. Validez. Notification auto à l''ANTS.\nDÉCLARATION OBLIGATOIRE DANS LES 24H.', 'Distribution', 'Hémovigilance', ARRAY['FEIR','effet indésirable','hémovigilance'], 15),
('Administration - Ajouter un utilisateur', E'Réservé aux administrateurs :\n1. Module Administration > Gestion des utilisateurs\n2. "Ajouter un utilisateur"\n3. Renseignez : nom, prénom, email, structure, profil\n4. Sélectionnez les rôles\n5. Email d''activation envoyé\n6. L''utilisateur définit son mot de passe', 'Administration', 'Utilisateurs', ARRAY['administration','utilisateur','rôle'], 16),
('Niveaux de support technique', E'Le support SIGDSTS est organisé en 3 niveaux :\nN1 : Chatbot IA 24/7 sur cette page. Résolution immédiate des questions courantes.\nN2 : Équipe support humain (Star Lab + Points Focaux). SLA : Critique 2h, Majeure 4h, Mineure 1 jour ouvré.\nN3 : Escalade éditeur pour bugs ou évolutions.\nSi le N1 ne résout pas, un ticket est créé pour le N2.', 'Support', 'Organisation', ARRAY['niveau','N1','N2','N3','SLA'], 17),
('Que faire en cas de bug bloquant', E'En cas de bug critique :\n1. NE PAS continuer la fonction défaillante (risque corruption)\n2. Notez l''heure et les dernières actions\n3. Capture d''écran de l''erreur\n4. Créez un ticket en sévérité CRITIQUE\n5. Sites pilotes : contactez aussi votre Point Focal ANTS\n6. SLA garanti : prise en charge sous 2h ouvrées', 'Support', 'Incidents', ARRAY['bug','critique','bloquant','urgent'], 18),
('Sécurité - Ne jamais partager son compte', E'Règles essentielles :\n- Ne JAMAIS partager identifiant/mot de passe\n- Toute action est tracée et imputée\n- Verrouillez votre session (Ctrl+L)\n- Changez votre mot de passe tous les 90 jours\n- Signalez toute connexion suspecte\nProtection des données patients : obligation légale.', 'Sécurité', 'Bonnes pratiques', ARRAY['sécurité','mot de passe','RGPD'], 19)
) AS v(title, content, module, category, keywords, display_order)
WHERE NOT EXISTS (SELECT 1 FROM public.support_knowledge_articles WHERE source = 'Guide SIGDSTS v11.0' LIMIT 1);
