// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvynepqulhflxtyymtzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eW5lcHF1bGhmbHh0eXltdHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTgxNTMsImV4cCI6MjA2MzE3NDE1M30.g1llr-Q6T3h06xFV7hCNRWZHG20wQHoBmp5zL0OAKh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Hardened fetch wrapper: timeout + 1 retry to avoid hung promises on flaky networks
// (root cause of ERR_TIMED_OUT loops on /app/chat over 2G/3G).
const TIMEOUT_MS = 12_000;
const hardenedFetch: typeof fetch = async (input, init) => {
  const url = typeof input === 'string' ? input : (input as Request).url;
  // Never wrap realtime/storage upload streams.
  const isRealtime = url.includes('/realtime/');
  if (isRealtime) return fetch(input, init);

  const attempt = async (signalTimeout: number) => {
    const ctrl = new AbortController();
    // Chain external abort signal if any
    const ext = init?.signal;
    if (ext) {
      if (ext.aborted) ctrl.abort(ext.reason);
      else ext.addEventListener('abort', () => ctrl.abort(ext.reason), { once: true });
    }
    const to = setTimeout(() => ctrl.abort(new DOMException('Timeout', 'TimeoutError')), signalTimeout);
    try {
      return await fetch(input, { ...init, signal: ctrl.signal });
    } finally {
      clearTimeout(to);
    }
  };

  try {
    return await attempt(TIMEOUT_MS);
  } catch (e: any) {
    const method = (init?.method || 'GET').toUpperCase();
    const idempotent = method === 'GET' || method === 'HEAD';
    const isAbort = e?.name === 'AbortError' || e?.name === 'TimeoutError';
    if (!idempotent || !isAbort) throw e;
    // One short retry for read requests
    await new Promise((r) => setTimeout(r, 400));
    return attempt(TIMEOUT_MS);
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: { fetch: hardenedFetch },
});
